### ISSUE TITLE
Could this be used to replicate the Navi reset bug kernel patch?

### ISSUE THREAD

**Issue by JaneSmith** [kobalicek/amdtweak#18]
There is a kernel patch available here: https://forum.level1techs.com/t/navi-reset-kernel-patch/147547

This patch uses the PowerPlay tables to turn the graphics card off and on again. This is done to work around an issue that affects people passing a Navi graphics card into a VM, where the card does not properly get reset between VM starts, and the host needs to be completely restarted to allow the VM to boot up again.

The kernel patch is likely not being merged into the kernel for a long time, and the distro that I am using it makes it quite difficult to run a custom kernel. So I was wondering if this project could be used to achieve the same effect?

Thanks.

**Comment by kobalicek** [comment]
Hi @JaneSmith,

I don't think you can do the same in this case. The patch writes to some registers that don't seem exposed via dev or sysfs. The amdtweak script just uses the functionality exposed by the GPU that allows to read/write powerplay data, but nothing else.

**Comment by JaneSmith** [comment]
Hmm. Okay then. Thanks a lot for taking the time to respond and clear that up!
