### ISSUE TITLE
Support PP Table of Version < 7

### ISSUE THREAD

**Issue by Perfect-Web** [kobalicek/amdtweak#2]

**Comment by kobalicek** [comment]
Please attach the PP table so I can take a look, and possibly the card you have. I only tested with RX480s

**Comment by Perfect-Web** [comment]
```
20000401000f20010000f0040006500303040f0f000f03070f0f0f000f000002000000000000000000000000000000000000000000000000000000000f0000000f0000000f0000000f0000000f0000000f0000000f0000000f000000050000000f0000000f0000000f000000010000000400000007000000000f00000000f0000000f0000000f0000000f0000000f0000000f0000000f000000000000f00000f00000000f00000f00000000f000000f0000000f000000f0000000f000000f1000000f000000f1000000f000000f1000000f000000f1000005000f03700000f000f053000000000ff00f2001f000000ff000ff1f00f300f00000000f000fff0000400f200000071000ff2100f50063000000f20006ff2006600f4000000630003ff300170076000000040000f3400f70007000000f500000f400ff00ff000000760001000030000f06132f0f071f2060f1f07100416060606060606003300070007050500000f0500000500060505070705000f1f0f000000000000000000000000000000000000100000001000000010000000000000
```
its for RX 470/480

**Comment by kobalicek** [comment]
I tested on my local copy, which is a bit improved version, but the Powerplay table of your data is Revision 4 (it uses a bit different format that's why the numbers are off). I'm not sure I would get the time to add all the missing tables required by version less than 7.

**Comment by Perfect-Web** [comment]
i could make a little donation in crypto if you could :)

**Comment by kobalicek** [comment]
Do you think you can send me the whole BIOS of your card? The PP table data you sent is kinda weird, I mean it reports structure size just 32 bytes and is half of size of tables that I have seen so far. Maybe it's just wrong data.

**Comment by Perfect-Web** [comment]
@kobalicek see if this works http://paste.ubuntu.com/25155493/

**Comment by kobalicek** [comment]
That file works, you can explore the data online here: https://kobalicek.com/vbiosed/

**Comment by Perfect-Web** [comment]
@kobalicek on the latest commit with that bios, the output is
```
{ StructureSize: 12338,
  TableFormatRevision: 48,
  TableContentRevision: 48 }
```

nothing else, is that right ? how can i see the list ?

**Comment by kobalicek** [comment]
Most of the time when you see empty structure it means that its version is not known to the tool. However, I tried your VBIOS and it works well, not sure why you are having these problems. I did some refactoring and committed my changes, I guess you no longer see warnings, will fix that

**Comment by Perfect-Web** [comment]
this is what i have
```
const fs = require("fs");
const vbios = require("./lib/vbios.js");

// Just what the script should do.
const DUMP = true;
const OVERWRITE = false;

const CARD_ID = 1;
const CARD_PP = `/sys/class/drm/card${CARD_ID}/device/pp_table`;

const buf = fs.readFileSync(CARD_PP);

// Decompose `buf` into a JS object:
const obj = vbios.$readObject({ buffer: buf, type: vbios.PowerPlayTable });

// Now, if everything went ok we will have an object describing the
// whole PP table. You can do whatever you want with it, including
// dumping its content, modifying it, etc.
if (DUMP)
  console.log(JSON.stringify(obj, null, 2));

// If you want to modify it, you can simply change the fields it
// provides. For example to change max TDP, which is stored in
// PowerTuneTable (subtable), do the following:
//obj.PowerTuneTable.TDP = 90;
console.log(obj);


// We modified the JS object and the data was not been synced with
// the original buffer yet. To save all values back to the buffer
// you have to call `$updateObject()`:
vbios.$updateObject({ buffer: buf, object: obj });

// Now the `buf` contains new changed data, the only thing to do
// next is to write it back.
if (OVERWRITE)
  fs.writeFileSync(CARD_PP, buf);



```

**Comment by kobalicek** [comment]
Can you pull and base your example on the newest `customtweak.js`? You should see additional log messages that can explain a bit what's happening.

**Comment by Perfect-Web** [comment]
i get this 
```
'[root]': Couldn't find versioned type 'PowerPlayTable$48'
Card '0' {"StructureSize":12338,"TableFormatRevision":48,"TableContentRevision":48}
'[root]': Couldn't find versioned type 'PowerPlayTable$48'
Card '1' {"StructureSize":12338,"TableFormatRevision":48,"TableContentRevision":48}

```

**Comment by kobalicek** [comment]
The data is wrong. Not sure why, but it's not PowerPlay table header for sure. The interesting thing is that the VBIOS you provided is valid and also contains a valid PP table.

I mean you can try other tools like OhGodATool to verify it's not vbios.js problem, but I'm convinced it would fail as well. I don't know if pp_table can point to anything else than a valid PowerPlay data, but it clearly does in this case

**Comment by Perfect-Web** [comment]
./ohgodatool -i 0 --show-mem
Unable to read entire PowerPlay table. (read 812, size was 12338)

**Comment by kobalicek** [comment]
Okay, so you don't have a valid PP table, I have no clue then :(

**Comment by Perfect-Web** [comment]
how can that happen ... this is odd indeed

**Comment by kobalicek** [comment]
I think it's a bug in the driver, it returns invalid data(but valid size)
