### ISSUE TITLE
Error : function writeFile(fileName, value, encoding) cannot work with binary data

### ISSUE THREAD

**Issue by Lucie2A** [kobalicek/amdtweak#9]
Hi,

found some solution for bugs #4 #5 and #7 : 
you want to use fs.writeFileSync() to write some binary data but the parms you are using are for UTF8 strings ... so this cannot work.

file: ./lib/iofs.js
lines: 146-154

Bug : 
```
function writeFile(fileName, value, encoding) {
  try {
    fs.writeFileSync(fileName, String(value), encoding);  <<<---
    return true;
  }
  catch (ex) {
    return false;
  }
}
```

Fix :
```
// you can remove 'encoding' param, it won't be used anymore
function writeFile(fileName, value, encoding) {
  try {
    fs.writeFile(fileName, value);  <<<---
    return true;
  }
  catch (ex) {
    return false;
  }
}
```

**Comment by kobalicek** [comment]
Thanks, I guess this was fixed by the PR. I really don't know if this was buggy from the beginning or something happened to node fs module, because I used amdtweak myself to tune some AMD GPUs.
